apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0001
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  nfs:
    path: <server_path>
    server: Server_IP
  persistentVolumeReclaimPolicy: Recycle
  claimRef:
    name: claim1
    namespace: default
